### ISSUE TITLE
Volumes

### ISSUE THREAD

**Issue by bobmulder** [granthbr/docker-raml-designer#1]
How am I able to set a volume to use my own local files?

**Comment by granthbr** [comment]
Hi Bob, First, build the container and run it. Then cp the files out of the container (i.e. make a directory in your local file system: /usr/local/lib/node_modules/api-designer then docker cp ram-designer:/usr/local/lib/node_modules/api-designer . ) Next, stop and delete the container (docker stop ramp-designer;docker rm raml-designer).Then run with the external volume set: docker run -d -p 8161:3000 -v ~/usr/local/lib/node_modules/api-designer: /usr/local/lib/node_modules/api-designer granthbr/docker-raml-designer api-designer. 
Then you should be able to store the file there. 
Good luck. 
Brandon

**Comment by bobmulder** [comment]
Hi @granthbr! Sorry for the short comment I sent. It was't very clear. Thank you for the explanation. Am I right that raml files are saved locally? I was hoping I could place my files somewhere else to get them with a git repository. I've managed to get this working in docker-compose using:

```
  docs:
    build: ./docker/docs
#    volumes:
#      - .:/var/www/html/docs
#    working_dir: /var/www/html/docs
    networks:
      project:
        ipv4_address: 22.0.0.210
```

However, I stuck at the volume / working_dir path. Can you help me setting up a volume so I can put my `.raml` files in my git repository (in `/docs`)?

Thanks in advance!

**Comment by bobmulder** [comment]
I tried the following:

```
    build: ./docker/docs
    volumes:
      - ./docs:/usr/local/lib/node_modules/api-designer
    networks:
      project:
        ipv4_address: 22.0.0.210
```

But it didn't work. I got the following error message:

```
ERROR: for docs  Container command 'api-designer' not found or does not exist.
Traceback (most recent call last):
  File "/usr/local/bin/docker-compose", line 9, in <module>
    load_entry_point('docker-compose==1.7.1', 'console_scripts', 'docker-compose')()
  File "/usr/local/lib/python2.7/dist-packages/compose/cli/main.py", line 63, in main
    log.error(e.msg)
AttributeError: 'ProjectError' object has no attribute 'msg'
```
